# Generated by Django 4.2 on 2025-07-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_menu_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablename', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=150)),
                ('searchname', models.CharField(max_length=200)),
                ('searchdata', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('tablename', 'username', 'searchname')},
            },
        ),
    ]
