# Generated by Django 4.2 on 2025-07-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customuser_address_customuser_email_notifications_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchpattern',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='language',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='website',
        ),
        migrations.AlterField(
            model_name='searchpattern',
            name='searchname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='searchpattern',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='GridLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
                ('layout_name', models.CharField(max_length=100)),
                ('layout_json', models.JSONField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('username', 'table_name', 'layout_name')},
            },
        ),
    ]
