# Generated by Django 4.2 on 2025-07-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_searchpattern_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('tabs_name', models.CharField(max_length=100)),
                ('tabs_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('username', 'tabs_name')},
            },
        ),
    ]
