# Generated by Django 4.2 on 2025-07-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tabinterface'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabinterface',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
